title: Simple Torch NFFT
description: NFFT and Fast Kernel Sums in PyTorch

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md

theme: jekyll-theme-cayman
